#!/bin/bash
# Political Fighting Game - Project Initialization Script
# This script sets up the development environment

set -e

echo "=== Political Fighting Game Initialization ==="

# Check for Godot
if command -v godot &> /dev/null; then
    echo "[OK] Godot found: $(godot --version 2>/dev/null || echo 'version check failed')"
else
    echo "[WARN] Godot not found. Please install Godot 4.x from https://godotengine.org"
fi

# Create Godot project file if not exists
if [ ! -f "game/project.godot" ]; then
    echo "Creating Godot project configuration..."
    cat > game/project.godot << 'EOF'
; Engine configuration file.
; Generated by Political Fighting Game initializer

[application]
config/name="Political Fighting Game"
config/description="A satirical multiplayer fighting game featuring controversial political figures"
run/main_scene="res://scenes/main_menu.tscn"
config/features=PackedStringArray("4.3", "Forward Plus")
config/icon="res://icon.svg"

[autoload]
GameManager="*res://scripts/core/game_manager.gd"
InputManager="*res://scripts/core/input_manager.gd"

[display]
window/size/viewport_width=1280
window/size/viewport_height=720
window/stretch/mode="viewport"
window/stretch/aspect="keep"

[input]
player1_left={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":65,"key_label":0,"unicode":97,"location":0,"echo":false,"script":null)]
}
player1_right={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":68,"key_label":0,"unicode":100,"location":0,"echo":false,"script":null)]
}
player1_jump={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":87,"key_label":0,"unicode":119,"location":0,"echo":false,"script":null)]
}
player1_attack={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":74,"key_label":0,"unicode":106,"location":0,"echo":false,"script":null)]
}

[rendering]
renderer/rendering_method="gl_compatibility"
EOF
    echo "[OK] Created game/project.godot"
fi

# Create directory structure
echo "Ensuring directory structure..."
mkdir -p game/scripts/core
mkdir -p game/scripts/characters
mkdir -p game/scripts/combat
mkdir -p game/scripts/network
mkdir -p game/scripts/ui
mkdir -p game/scenes/characters
mkdir -p game/scenes/stages
mkdir -p game/scenes/ui
mkdir -p game/resources/moves
mkdir -p game/resources/stats
mkdir -p game/resources/characters
mkdir -p game/mods
mkdir -p assets/sprites/characters
mkdir -p assets/sprites/stages
mkdir -p assets/audio/sfx
mkdir -p assets/audio/music
mkdir -p docs
mkdir -p tools
mkdir -p builds/web
mkdir -p builds/windows
mkdir -p builds/linux
mkdir -p builds/android

echo "[OK] Directory structure created"

echo ""
echo "=== Initialization Complete ==="
echo "Next steps:"
echo "  1. Open game/ folder in Godot 4.x"
echo "  2. Run tests: godot --headless --script scripts/test_runner.gd"
echo "  3. Build: ./build.sh [platform]"
